/**
 * The withRestless wrapping loader.
 *
 * Runs on every `app/(**)/route.<ext>` module in both bundlers (webpack via
 * a rule withRestless injects with `enforce: 'pre'`; Turbopack via
 * `turbopack.rules` — Turbopack executes loaders through webpack's own
 * loader-runner, so the same string-in/string-out contract applies) and
 * replaces the module's source with a facade that:
 *
 *   1. imports the original module via a `?__restless_original__`
 *      query-suffixed self-import (distinct module identity, same file),
 *   2. imports `restless.config.*` when the plugin discovered one,
 *   3. re-exports the original's segment-config exports CONCRETELY
 *      (Next can't handle `export * from` in route modules, and dev mode
 *      errors on spurious `default` exports — so nothing is star- or
 *      default-re-exported), and
 *   4. shadows each detected HTTP-method export with a wrapped version.
 *
 * The on-disk file is untouched, so Next's route type-checking and
 * segment-config static analysis (both read the original source) are
 * unaffected.
 *
 * This module is deliberately dependency-free (node:path only) and imports
 * nothing from the rest of the SDK: webpack `require()`s loaders by absolute
 * path, and Turbopack JSON-serializes loader options — the less this file
 * touches, the fewer ways that can break.
 */
import path from "node:path";

export interface RestlessLoaderOptions {
  /** Absolute path of the discovered restless.config.*; absent = zero-config. */
  configPath?: string;
  /** Absolute path of the Next project root (where app/ or src/app lives). */
  projectRoot: string;
  /** Root-relative posix globs of route files to leave unwrapped. */
  exclude?: string[];
  /** Log every wrap/skip decision at build time. */
  debug?: boolean;
  /** pageExtensions from next.config (default tsx,ts,jsx,js). */
  exts?: string[];
}

/** Subset of the webpack/Turbopack loader context the loader relies on. */
interface LoaderContext {
  resourcePath: string;
  resourceQuery?: string;
  getOptions?: () => RestlessLoaderOptions;
  query?: unknown;
  emitWarning?: (err: Error) => void;
}

export const ORIGINAL_QUERY = "__restless_original__";
const BANNER =
  "/* auto-generated by @restlessai/sdk withRestless — restless-disable */";

const HTTP_METHODS = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "HEAD",
  "OPTIONS",
] as const;

/**
 * The rest of a route module's legal export surface (Next rejects arbitrary
 * exports from route files, so this list is closed). Re-exported verbatim.
 */
const SEGMENT_EXPORTS = [
  "dynamic",
  "dynamicParams",
  "revalidate",
  "fetchCache",
  "runtime",
  "preferredRegion",
  "maxDuration",
  "generateStaticParams",
] as const;

const DEFAULT_EXTS = ["tsx", "ts", "jsx", "js"];

/**
 * Blank out comment bodies and string contents (quotes kept) so export
 * detection can't be fooled by `// export function GET` in a comment or an
 * SSE payload string. Template-literal interpolation and regex literals are
 * not modeled — the worst case is a mis-detection that either skips a file
 * (warned) or emits a wrapper for an absent method (wrapRouteHandler passes
 * `undefined` through untouched).
 */
function stripCommentsAndStrings(src: string): string {
  let out = "";
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    const next = src[i + 1];
    if (c === "/" && next === "/") {
      while (i < n && src[i] !== "\n") i++;
    } else if (c === "/" && next === "*") {
      i += 2;
      while (i < n && !(src[i] === "*" && src[i + 1] === "/")) i++;
      i += 2;
    } else if (c === '"' || c === "'" || c === "`") {
      const quote = c;
      out += quote;
      i++;
      while (i < n && src[i] !== quote) {
        if (src[i] === "\\") i++;
        i++;
      }
      out += quote;
      i++;
    } else {
      out += c;
      i++;
    }
  }
  return out;
}

/** Names exported via `export { a, b as c }` lists (value exports only). */
function exportListNames(stripped: string): Set<string> {
  const names = new Set<string>();
  const listRe = /export\s*(type\s*)?\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = listRe.exec(stripped))) {
    if (m[1]) continue; // export type { ... } — types only
    for (const rawItem of m[2].split(",")) {
      const item = rawItem.trim();
      if (!item || item.startsWith("type ")) continue;
      const asMatch = item.match(/\bas\s+([A-Za-z_$][\w$]*)$/);
      names.add(asMatch ? asMatch[1]! : item.split(/\s+/)[0]!);
    }
  }
  return names;
}

function detectExports(stripped: string, candidates: readonly string[]) {
  const listed = exportListNames(stripped);
  return candidates.filter((name) => {
    if (listed.has(name)) return true;
    return (
      new RegExp(`export\\s+(?:async\\s+)?function\\s+${name}\\b`).test(
        stripped,
      ) ||
      new RegExp(`export\\s+(?:const|let|var)\\s+${name}\\b`).test(stripped) ||
      new RegExp(`export\\s+(?:const|let|var)\\s*[{[][^}\\]]*\\b${name}\\b`).test(
        stripped,
      )
    );
  });
}

/** Minimal glob → RegExp: supports `**`, `*`, `?` over posix paths. */
function globToRegExp(glob: string): RegExp {
  const cleaned = glob.replace(/^\.\//, "");
  let re = "";
  let i = 0;
  while (i < cleaned.length) {
    const c = cleaned[i];
    if (c === "*") {
      if (cleaned[i + 1] === "*") {
        // `**/` matches zero or more whole segments; bare `**` matches any.
        if (cleaned[i + 2] === "/") {
          re += "(?:[^/]+/)*";
          i += 3;
        } else {
          re += ".*";
          i += 2;
        }
      } else {
        re += "[^/]*";
        i += 1;
      }
    } else if (c === "?") {
      re += "[^/]";
      i += 1;
    } else {
      re += c!.replace(/[.+^${}()|[\]\\]/g, "\\$&");
      i += 1;
    }
  }
  return new RegExp(`^${re}$`);
}

function toPosix(p: string): string {
  return p.replace(/\\/g, "/");
}

/** Relative import specifier from the route file's dir to the config file. */
function configSpecifier(resourcePath: string, configPath: string): string {
  const rel = toPosix(path.relative(path.dirname(resourcePath), configPath));
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function buildFacade(args: {
  selfSpecifier: string;
  configSpecifier?: string;
  methods: string[];
  segmentExports: string[];
}): string {
  const self = JSON.stringify(args.selfSpecifier);
  const lines = [
    BANNER,
    `import * as __restless_orig from ${self};`,
  ];
  if (args.configSpecifier) {
    lines.push(
      `import * as __restless_cfgmod from ${JSON.stringify(args.configSpecifier)};`,
    );
  }
  lines.push(
    `import { wrapRouteHandler as __restless_wrap } from "@restlessai/sdk/next";`,
  );
  for (const name of args.segmentExports) {
    lines.push(`export { ${name} } from ${self};`);
  }
  if (args.configSpecifier) {
    lines.push(
      `const __restless_cfg = __restless_cfgmod.default ?? undefined;`,
      // One warning per process, not per route module.
      `if (__restless_cfg === undefined && !globalThis.__restless_cfg_warned) {`,
      `  globalThis.__restless_cfg_warned = true;`,
      `  console.warn("[@restlessai/sdk] restless.config has no default export — running in zero-config mode. Export defineConfig({...}) as default.");`,
      `}`,
    );
  } else {
    lines.push(`const __restless_cfg = undefined;`);
  }
  for (const method of args.methods) {
    lines.push(
      `export const ${method} = __restless_wrap(__restless_orig.${method}, __restless_cfg, ${JSON.stringify(method)});`,
    );
  }
  return lines.join("\n") + "\n";
}

function restlessLoader(this: LoaderContext, source: string): string {
  const opts: RestlessLoaderOptions =
    (this.getOptions ? this.getOptions() : (this.query as RestlessLoaderOptions)) ||
    ({ projectRoot: "" } as RestlessLoaderOptions);

  const debug = (msg: string) => {
    if (opts.debug) console.log(`[@restlessai/sdk withRestless] ${msg}`);
  };
  const warn = (msg: string) => {
    const err = new Error(`[@restlessai/sdk withRestless] ${msg}`);
    if (this.emitWarning) this.emitWarning(err);
    else console.warn(err.message);
  };

  // 1. The original-module request must compile untouched (recursion guard).
  if ((this.resourceQuery || "").includes(ORIGINAL_QUERY)) return source;

  // 2. Idempotency — never wrap our own facade.
  if (source.startsWith(BANNER)) return source;

  // 3. Precise path scoping. Load-bearing under Turbopack, where the rule
  //    glob is `**/`-prefixed (globs resolve against the lockfile root, not
  //    the app dir) and can over-match, e.g. inside node_modules.
  const resource = toPosix(this.resourcePath);
  const root = toPosix(opts.projectRoot || "");
  const rel = root && resource.startsWith(root + "/")
    ? resource.slice(root.length + 1)
    : null;
  if (!rel || rel.includes("node_modules/") || !/^(?:src\/)?app\//.test(rel)) {
    return source;
  }
  const exts = opts.exts?.length ? opts.exts : DEFAULT_EXTS;
  const base = rel.split("/").pop()!;
  if (!exts.some((ext) => base === `route.${ext}`)) return source;

  // 4. User excludes.
  for (const glob of opts.exclude || []) {
    if (globToRegExp(glob).test(rel)) {
      debug(`skip (excluded): ${rel}`);
      return source;
    }
  }

  // 5. Per-file escape comment.
  if (/(?:\/\/|\/\*)\s*@?restless[- ]disable/.test(source.slice(0, 2048))) {
    debug(`skip (restless-disable): ${rel}`);
    return source;
  }

  // 6. Edge-runtime routes: the SDK's Node build can't bundle for the edge
  //    runtime yet (fs-backed settings/env loading). Raw source — string
  //    literals must be visible to this check.
  if (
    /export\s+(?:const|let|var)\s+runtime\s*(?::[^=\n]*)?=\s*["'](?:experimental-)?edge["']/.test(
      source,
    )
  ) {
    warn(
      `${rel} runs on the edge runtime — not auto-wrapped (v1 limitation). Capture for this route is disabled.`,
    );
    return source;
  }

  const stripped = stripCommentsAndStrings(source);

  // 7. Opaque re-export shapes: we can't enumerate what `export *` carries,
  //    and Next chokes on a facade that star-re-exports. Punt with a warning.
  if (/export\s*\*/.test(stripped)) {
    warn(
      `${rel} uses \`export *\` — not auto-wrapped. Re-export handlers by name, or wrap manually (see install.md).`,
    );
    return source;
  }

  const methods = detectExports(stripped, HTTP_METHODS);
  if (methods.length === 0) {
    debug(`skip (no HTTP method exports found): ${rel}`);
    return source;
  }
  const segmentExports = detectExports(stripped, SEGMENT_EXPORTS);

  debug(
    `wrap: ${rel} methods=[${methods.join(",")}] segment=[${segmentExports.join(",")}]`,
  );

  return buildFacade({
    selfSpecifier: `./${base}?${ORIGINAL_QUERY}`,
    configSpecifier: opts.configPath
      ? configSpecifier(this.resourcePath, opts.configPath)
      : undefined,
    methods,
    segmentExports,
  });
}

export default restlessLoader;

// Webpack require()s loaders by path and expects the function itself on
// module.exports; tsup's CJS interop would otherwise leave it on `.default`.
// The `default` property is re-attached for ESM-shaped consumers (Turbopack
// resolves the package subpath, which maps to this same CJS artifact).
declare const module: { exports: unknown } | undefined;
if (typeof module !== "undefined" && module) {
  module.exports = Object.assign(restlessLoader, {
    default: restlessLoader,
    ORIGINAL_QUERY,
  });
}
